# Generated by Django 5.0.6 on 2024-12-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=0, help_text='Foydalanuvchining Yoshi'),
        ),
    ]
